<?php

/*
 * This file is part of Composer Virtual Environment Plugin.
 *
 * (c) Stephan Jorek <stephan.jorek@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sjorek\Composer\VirtualEnvironment\Config;

use Composer\Composer;

/**
 * @author Stephan Jorek <stephan.jorek@gmail.com>
 */
class FileConfiguration extends AbstractConfiguration implements FileConfigurationInterface
{
    public $filePath;

    protected $blacklist = array('info');

    const INFO = array(
        'virtual environment configuration file',
        'generated by the composer-virtual-environment-plugin',
    );

    /**
     * @param Composer $composer
     * @param string   $file
     */
    public function __construct(Composer $composer, $file)
    {
        parent::__construct($composer);
        $this->filePath = $file;
    }

    /**
     * {@inheritDoc}
     * @see FileConfigurationInterface::file()
     */
    public function file()
    {
        return $this->filePath;
    }

    /**
     * {@inheritDoc}
     * @see FileConfigurationInterface::load()
     */
    public function load()
    {
        if (!file_exists($this->filePath)) {
            return false;
        }

        $json = file_get_contents($this->filePath, false);
        if ($json === false) {
            return false;
        }
        $data = json_decode($json, true, 3, JSON_OBJECT_AS_ARRAY);
        if (null === $data && JSON_ERROR_NONE !== json_last_error()) {
            return false;
        }
        if (!is_array($data)) {
            return false;
        }

        $blacklist = $this->blacklist;
        $this->data = array_filter(
            $data,
            function ($key) use ($blacklist) {
                return !in_array($key, $blacklist, true);
            },
            ARRAY_FILTER_USE_KEY
        );
        $this->dirty = false;

        return true;
    }

    /**
     * {@inheritDoc}
     * @see FileConfigurationInterface::save()
     */
    public function save($force = false)
    {
        if ($this->dirty || $force) {
            $data = array_merge(
                array(
                    'info' => static::INFO,
                ),
                $this->export()
            );
            $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES /* | JSON_FORCE_OBJECT */);
            if ($json === false) {
                return false;
            }
            $result = file_put_contents($this->filePath, $json . PHP_EOL);
            if ($result === false) {
                return false;
            }
            $this->dirty = false;
        }

        return !$this->dirty;
    }
}
