<?php

/*
 * This file is part of Composer Virtual Environment Plugin.
 *
 * (c) Stephan Jorek <stephan.jorek@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sjorek\Composer\VirtualEnvironment\Config;

use Composer\Composer;
use Composer\Factory;

/**
 * @author Stephan Jorek <stephan.jorek@gmail.com>
 */
class GlobalConfiguration extends FileConfiguration
{
    protected $blacklist = array('info', 'name');

    const INFO = 'Global virtual environment configuration generated by the composer-virtual-environment-plugin';

    /**
     * @param Composer $composer
     */
    public function __construct(Composer $composer)
    {
        $recipe = Factory::getComposerFile();
        $home = $composer->getConfig()->get('home');
        $filename = $home . DIRECTORY_SEPARATOR . basename($recipe, '.json') . '.venv';
        parent::__construct($composer, $filename);
    }
}
