<?php

/*
 * This file is part of Composer Virtual Environment Plugin.
 *
 * (c) Stephan Jorek <stephan.jorek@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sjorek\Composer\VirtualEnvironment\Config;

use Composer\Composer;
use Composer\Factory;

/**
 * @author Stephan Jorek <stephan.jorek@gmail.com>
 */
class LocalConfiguration extends FileConfiguration
{
    const INFO = array(
        'local virtual environment configuration',
        'generated by the composer-virtual-environment-plugin',
    );

    /**
     * @param Composer $composer
     */
    public function __construct(Composer $composer)
    {
        $recipe = Factory::getComposerFile();
        $fileName = basename($recipe, '.json') . '-venv.json';
        parent::__construct($composer, dirname($recipe) . DIRECTORY_SEPARATOR . $fileName);
    }
}
